export interface TeamDto {
  name: string;
  email: string;
  password?: string;
  password2?: string;
  phone: string;
  accommodation: string;
  firstName: string;
  lastName: string;
  tshirt: string;
  food: string;
  firstName2: string;
  lastName2: string;
  tshirt2: string;
  food2: string;
  firstName3: string;
  lastName3: string;
  tshirt3: string;
  food3: string;
  firstName4: string;
  lastName4: string;
  tshirt4: string;
  food4: string;
  firstName5: string;
  lastName5: string;
  tshirt5: string;
  food5: string;
  payId: string;
}
